### ISSUE TITLE
Remember Me Button Not Working After Upgrading to Rails 7.1

### ISSUE THREAD

**Issue by keshavbiswa** [neat-space/sprint-spades#32]
# Description

After upgrading to Rails 7.1, the "remember me" functionality has stopped working. This issue has been commented out in the sessions/new.html.erb file.

```erb
<%# TODO:- Figure out why remember me doesn't work at all!!!!  %>
<%#= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
```

# Steps to Reproduce
- Uncomment the above lines from devise/sessions/new.html.erb
- Attempt to use the "remember me" functionality during login.

# Expected Behavior
Users should get logged in 

Actual Behavior
Users are redirected to the home page without getting logged in.

**Comment by Animesh-Ghosh** [comment]
I was able to reproduce this. Took me a couple hours tbh with the devise + warden rabbit hole.

Created a new test app with devise with the same Ruby and Rails version. The only difference that got highlighted (after going through some Rails issues) was in the way the `remember_user` cookie was being generated.

sprint-spades got `"[remember_user"` sent back by the server, whereas the other test app got `"remember_user"` sent back, which correctly logged in the user.

The fix seems to be to downgrade `rack`, based on [this](https://github.com/rails/rails/issues/49422#issuecomment-1745186817) comment.

Let me know what you think @keshavbiswa.

Sharing the issues for reference:
https://github.com/rails/rails/issues/50229
https://github.com/rails/rails/issues/49422

**Comment by Animesh-Ghosh** [comment]
One more lead: https://github.com/rails/rails/issues/50702#issuecomment-1886385153

We might be able to get away with just upgrading Puma to a newer version. Will check and report back how that goes.

**Comment by keshavbiswa** [comment]
@Animesh-Ghosh Thanks!!! 

I'm ok with upgrading puma. Would you like to create a PR for it? 

Thanks for going down this rabbit hole 😅

**Comment by Animesh-Ghosh** [comment]
Will do once I test upgrading Puma indeed fixes the issue.
